[package]
strategy = "build"
name = "xz"

source_url = "https://github.com/tukaani-project/xz"
version_pattern = "v{{version}}"
script = """
[ -f configure ] || ./autogen.sh
./configure --prefix=$PREFIX --disable-shared --enable-static
make -j$JOBS
make install
"""
