[package]
strategy = "build"
name = "m4"

source_url = "https://git.savannah.gnu.org/git/m4.git"
version_pattern = "v{{version}}"
download_url_template = "https://ftp.gnu.org/gnu/m4/m4-{{version}}.tar.gz"
script = """
./configure --prefix=$PREFIX
make -j$JOBS
make install
"""
