[package]
strategy = "build"
name = "git"

source_url = "https://github.com/git/git"
version_pattern = "v{{version}}"
dependencies = ["openssl@3.5", "curl", "zlib", "expat", "pcre2"]
script = """
make prefix=$PREFIX \
    NO_GETTEXT=1 \
    NO_TCLTK=1 \
    OPENSSLDIR=$DEP_OPENSSL \
    CURLDIR=$DEP_CURL \
    EXPATDIR=$DEP_EXPAT \
    LIBPCREDIR=$DEP_PCRE2 \
    -j$JOBS all
make prefix=$PREFIX install
"""
