[package]
strategy = "build"
name = "glib"
source_url = "https://github.com/GNOME/glib"
tag_pattern = "{{version}}"
version_pattern = "2.82.*"
dependencies = ["libffi", "pcre2", "gettext", "zlib"]
script = """
meson setup build \
    --prefix=$PREFIX \
    --buildtype=release \
    -Dtests=false \
    -Dinstalled_tests=false
meson compile -C build
meson install -C build
"""
