[package]
strategy = "build"
name = "cairo"
source_url = "https://github.com/nicholasbishop/cairo"
tag_pattern = "{{version}}"
version_pattern = "1.18.*"
dependencies = ["freetype", "fontconfig", "libpng", "pixman", "glib", "zlib"]
script = """
meson setup build \
    --prefix=$PREFIX \
    --buildtype=release \
    -Dtests=disabled \
    -Dquartz=enabled \
    -Dfreetype=enabled \
    -Dfontconfig=enabled \
    -Dpng=enabled
meson compile -C build
meson install -C build
"""
