[package]
strategy = "build"
name = "pango"
source_url = "https://github.com/nicholasbishop/pango"
tag_pattern = "{{version}}"
version_pattern = "1.54.*"
dependencies = ["glib", "harfbuzz", "freetype", "fontconfig", "cairo", "fribidi"]
script = """
meson setup build \
    --prefix=$PREFIX \
    --buildtype=release \
    -Dintrospection=disabled
meson compile -C build
meson install -C build
"""
