[package]
strategy = "build"
name = "ninja"

source_url = "https://github.com/ninja-build/ninja"
tag_pattern = "v{{version}}"
version_pattern = "^1.12"
dependencies = ["cmake"]
script = """
cmake -B build -DCMAKE_BUILD_TYPE=Release
cmake --build build --parallel $JOBS
mkdir -p $PREFIX/bin
cp build/ninja $PREFIX/bin/
"""
