[package]
strategy = "build"
name = "libffi"

source_url = "https://github.com/libffi/libffi"
tag_pattern = "v{{version}}"
dependencies = ["autoconf", "automake", "libtool"]
script = """
[ -f configure ] || ./autogen.sh
./configure --prefix=$PREFIX --disable-shared --enable-static
make -j$JOBS
make install
"""
