[package]
strategy = "build"
name = "expat"

source_url = "https://github.com/libexpat/libexpat"
tag_pattern = "R_{{version}}"
version_pattern = "2_6_*"
dependencies = ["autoconf", "automake"]
script = """
cd expat
./buildconf.sh
./configure --prefix=$PREFIX \
    --without-docbook
make -j$JOBS
make install
"""
