[package]
strategy = "build"
name = "gettext"

source_url = "https://git.savannah.gnu.org/git/gettext.git"
version_pattern = "v{{version}}"
dependencies = ["ncurses"]
script = """
./configure --prefix=$PREFIX \
    --disable-java \
    --disable-csharp \
    --without-git \
    --without-cvs \
    --without-xz
make -j$JOBS
make install
"""
