[package]
strategy = "build"
name = "gettext"

source_url = "https://github.com/autotools-mirror/gettext"
tag_pattern = "v{{version}}"
version_pattern = "0.22*"
dependencies = ["ncurses"]
script = """
./configure --prefix=$PREFIX \
    --disable-java \
    --disable-csharp \
    --without-git \
    --without-cvs \
    --without-xz
make -j$JOBS
make install
"""
