[package]
strategy = "build"
name = "bzip2"

source_url = "https://sourceware.org/git/bzip2.git"
version_pattern = "bzip2-{{version}}"
version_pattern = "^1.0"
download_url_template = "https://sourceware.org/pub/bzip2/bzip2-{{version}}.tar.gz"
script = """
make -j$JOBS CC=clang PREFIX=$PREFIX CFLAGS="-Wl,-headerpad_max_install_names" LDFLAGS="-Wl,-headerpad_max_install_names"
make install CC=clang PREFIX=$PREFIX CFLAGS="-Wl,-headerpad_max_install_names" LDFLAGS="-Wl,-headerpad_max_install_names"
"""
