[package]
strategy = "build"
name = "gperf"
source_url = "https://github.com/nicholasbishop/gperf"
tag_pattern = "v{{version}}"
version_pattern = "3.1*"
dependencies = []
script = """
./configure --prefix=$PREFIX
make -j$JOBS
make install
"""
