[package]
strategy = "build"
name = "fontconfig"
source_url = "https://github.com/nicholasbishop/fontconfig"
tag_pattern = "{{version}}"
version_pattern = "2.15.*"
dependencies = ["freetype", "expat", "gperf"]
script = """
meson setup build \
    --prefix=$PREFIX \
    --buildtype=release \
    -Ddoc=disabled \
    -Dtests=disabled \
    -Dtools=disabled
meson compile -C build
meson install -C build
"""
