[package]
strategy = "build"
name = "texinfo"

source_url = "https://git.savannah.gnu.org/git/texinfo.git"
version_pattern = "texinfo-{{version}}"
dependencies = ["ncurses"]
script = """
./autogen.sh
./configure --prefix=$PREFIX
make -j$JOBS
make install
"""
