[package]
strategy = "build"
name = "texinfo"

source_url = "https://github.com/autotools-mirror/texinfo"
tag_pattern = "texinfo-{{version}}"
version_pattern = "~7.1"
dependencies = ["ncurses"]
script = """
./autogen.sh
./configure --prefix=$PREFIX
make -j$JOBS
make install
"""
