[package]
strategy = "build"
name = "libtool"

source_url = "https://git.savannah.gnu.org/git/libtool.git"
version_pattern = "v{{version}}"
download_url_template = "https://ftp.gnu.org/gnu/libtool/libtool-{{version}}.tar.gz"
script = """
./configure --prefix=$PREFIX
make -j$JOBS
make install
"""
