[package]
strategy = "build"
name = "libtool"

source_url = "https://github.com/autotools-mirror/libtool"
tag_pattern = "v{{version}}"
version_pattern = "^2.4"
dependencies = ["m4", "autoconf", "automake"]
script = """
./bootstrap
./configure --prefix=$PREFIX
make -j$JOBS
make install
"""
