[package]
strategy = "build"
name = "libxslt"

source_url = "https://github.com/GNOME/libxslt"
tag_pattern = "v{{version}}"
version_pattern = "^1.1"
dependencies = ["libxml2"]
script = """
./autogen.sh --prefix=$PREFIX \
    --disable-shared \
    --enable-static \
    --without-python \
    --with-libxml-prefix=$DEP_LIBXML2
make -j$JOBS
make install
"""
