[package]
strategy = "build"
name = "autoconf"

source_url = "https://git.savannah.gnu.org/git/autoconf.git"
version_pattern = "v{{version}}"
download_url_template = "https://ftp.gnu.org/gnu/autoconf/autoconf-{{version}}.tar.gz"
dependencies = ["m4"]
script = """
./configure --prefix=$PREFIX
make -j$JOBS
make install
"""
