[package]
strategy = "build"
name = "wget"

source_url = "https://github.com/mirror/wget"
tag_pattern = "v{{version}}"
version_pattern = "1.24*"
dependencies = ["openssl@3.5", "zlib"]
script = """
./bootstrap
./configure --prefix=$PREFIX \
    --with-ssl=openssl \
    --with-openssl-dir=$DEP_OPENSSL \
    --with-zlib=$DEP_ZLIB
make -j$JOBS
make install
"""
