[package]
strategy = "build"
name = "freetype"
source_url = "https://github.com/freetype/freetype"
tag_pattern = "VER-{{version}}"
dependencies = ["libpng", "zlib", "bzip2"]
script = """
./autogen.sh
./configure --prefix=$PREFIX \
    --with-zlib=yes \
    --with-bzip2=yes \
    --with-png=yes \
    --with-harfbuzz=no \
    --enable-freetype-config
make -j$JOBS
make install
"""
