[package]
strategy = "build"
name = "bison"

source_url = "https://github.com/autotools-mirror/bison"
tag_pattern = "v{{version}}"
version_pattern = "^3.8"
dependencies = ["m4"]
script = """
./bootstrap
./configure --prefix=$PREFIX
make -j$JOBS
make install
"""
