[package]
strategy = "build"
name = "gdbm"

source_url = "https://github.com/sailfishos-mirror/gdbm"
tag_pattern = "v{{version}}"
version_pattern = "1.24*"
script = """
./configure --prefix=$PREFIX --disable-shared --enable-static
make -j$JOBS
make install
"""
