[package]
strategy = "build"
name = "libiconv"

source_url = "https://github.com/gnu-mirror-unofficial/libiconv"
version_pattern = "v{{version}}"
dependencies = []
script = """
./configure --prefix=$PREFIX \
    --enable-extra-encodings
make -j$JOBS
make install
"""
