[package]
strategy = "build"
name = "meson"
source_url = "https://github.com/mesonbuild/meson"
version_pattern = "{{version}}"
dependencies = ["python"]
script = """
python3 -m pip install --no-build-isolation --prefix=$PREFIX .
"""
