[package]
strategy = "build"
name = "libpng"

source_url = "https://github.com/pnggroup/libpng"
version_pattern = "v{{version}}"
dependencies = ["zlib"]
script = """
./configure --prefix=$PREFIX --disable-shared --enable-static \
    CPPFLAGS="-I$DEP_ZLIB/include" \
    LDFLAGS="-L$DEP_ZLIB/lib"
make -j$JOBS
make install
"""
