[package]
strategy = "build"
name = "flex"

source_url = "https://github.com/westes/flex"
version_pattern = "v{{version}}"
dependencies = ["m4", "autoconf", "automake"]
script = """
./autogen.sh
./configure --prefix=$PREFIX --disable-shared
make -j$JOBS
make install
"""
