[package]
strategy = "build"
name = "perl"

source_url = "https://github.com/Perl/perl5"
version_pattern = "v{{version}}"
dependencies = []
script = """
./Configure -des -Dprefix=$PREFIX -Dusethreads -Duseshrplib=false
make -j$JOBS
make install
"""
