[package]
strategy = "build"
name = "fribidi"
source_url = "https://github.com/fribidi/fribidi"
tag_pattern = "v{{version}}"
version_pattern = "^1.0"
dependencies = ["autoconf", "automake", "libtool"]
script = """
./autogen.sh
./configure --prefix=$PREFIX
make -j$JOBS
make install
"""
