[package]
strategy = "build"
name = "harfbuzz"
source_url = "https://github.com/harfbuzz/harfbuzz"
tag_pattern = "{{version}}"
version_pattern = "^12"
dependencies = ["freetype", "icu4c", "autoconf", "automake", "libtool"]
script = """
./autogen.sh
./configure --prefix=$PREFIX \
    --with-freetype=yes \
    --with-glib=no \
    --with-icu=yes \
    --with-cairo=no \
    --with-gobject=no
make -j$JOBS
make install
"""
