[package]
strategy = "build"
name = "harfbuzz"
source_url = "https://github.com/harfbuzz/harfbuzz"
tag_pattern = "{{version}}"
version_pattern = "10.*"
dependencies = ["freetype", "glib", "icu4c"]
script = """
meson setup build \
    --prefix=$PREFIX \
    --buildtype=release \
    -Dfreetype=enabled \
    -Dglib=enabled \
    -Dicu=enabled \
    -Dcairo=disabled \
    -Dtests=disabled \
    -Ddocs=disabled
meson compile -C build
meson install -C build
"""
