[package]
strategy = "build"
name = "pixman"
source_url = "https://github.com/nicholasbishop/pixman"
tag_pattern = "pixman-{{version}}"
version_pattern = "0.44.*"
dependencies = []
script = """
meson setup build \
    --prefix=$PREFIX \
    --buildtype=release \
    -Dtests=disabled \
    -Ddemos=disabled
meson compile -C build
meson install -C build
"""
