[package]
strategy = "build"
name = "cmake"

source_url = "https://github.com/Kitware/CMake"
version_pattern = "v{{version}}"
dependencies = []
script = """
./bootstrap --prefix=$PREFIX --parallel=$JOBS -- \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_USE_OPENSSL=OFF
make -j$JOBS
make install
"""
