[package]
name = "zlib"
strategy = "build"
source_url = "https://github.com/madler/zlib"
tag_pattern = "v{{version}}"
version_pattern = "^1\\.3\\."
script = """
./configure --prefix=$PREFIX --static
make -j$JOBS
make install
"""
