[package]
name = "zlib"
strategy = "build"
source_url = "https://github.com/madler/zlib"
version_pattern = "v{{version}}"
script = """
./configure --prefix=$PREFIX --static
make -j$JOBS
make install
"""
